[package]
name = "ri-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ri-agent-lua = { path = "../lua" }
anyhow = "1"
rusqlite = { version = "0.38", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots"] }
futures-util = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "process", "io-util", "io-std", "time", "sync"] }
secrecy = "0.10"
tempfile = "3"
serde_json = "1.0.149"
serde_yaml_ng = "0.10"
serde = { version = "1", features = ["derive"] }
